import { readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import ts from 'typescript';
import openapiTS, { astToString, type OpenAPI3 } from 'openapi-typescript';

type ObjectValue = Record<string, unknown>;
export type OperationMetadata = {
  operationId: string;
  method: string;
  path: string;
  tags: string[];
  access: 'read' | 'write';
  requiredPermissions: string[] | null;
  idempotency: { header: string; required: boolean; description: string | null } | null;
};
const METHODS = ['get', 'head', 'post', 'put', 'patch', 'delete', 'options', 'trace'];
const MAX_BYTES = 8 * 1024 * 1024;
const ROOT = new URL('../', import.meta.url);
const HEADER = '// Generated by scripts/generate-operations.ts. Do not edit.\n';

function object(value: unknown): ObjectValue {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('Expected an OpenAPI object');
  return value as ObjectValue;
}

function strings(value: unknown): string[] {
  if (!Array.isArray(value) || value.some(item => typeof item !== 'string' || !item)) {
    throw new Error('Expected an array of nonempty strings');
  }
  return value as string[];
}

function lookup(spec: ObjectValue, ref: unknown): unknown {
  if (typeof ref !== 'string' || !ref.startsWith('#/')) throw new Error('Only local references are allowed');
  let value: unknown = spec;
  for (const part of decodeURIComponent(ref.slice(2)).split('/')) {
    if (/~(?:[^01]|$)/.test(part)) throw new Error('Invalid reference escape');
    const key = part.replace(/~1/g, '/').replace(/~0/g, '~');
    const parent = object(value);
    if (!Object.hasOwn(parent, key)) throw new Error('Unresolved local reference');
    value = parent[key];
  }
  return value;
}

export function qualifyEmbeddedDefinitions(input: unknown): unknown {
  const embedded: Record<string, unknown> = {};
  let nodes = 0;
  function visit(value: unknown, scopes: Record<string, string> = {}, depth = 0): unknown {
    if (++nodes > 500_000 || depth > 100) throw new Error('Spec exceeds normalization bound');
    if (Array.isArray(value)) return value.map(child => visit(child, scopes, depth + 1));
    if (!value || typeof value !== 'object') return value;
    const item = value as ObjectValue;
    const local = { ...scopes };
    if (item.definitions) {
      for (const key of Object.keys(object(item.definitions)).sort()) {
        const name = '__embeddedDefinition' + Object.keys(embedded).length;
        local[key] = '#/components/schemas/' + name;
        embedded[name] = null;
      }
      for (const [key, schema] of Object.entries(object(item.definitions))) {
        embedded[local[key]!.split('/').pop()!] = visit(schema, local, depth + 1);
      }
    }
    return Object.fromEntries(Object.entries(item).filter(([key]) => key !== 'definitions').map(([key, child]) => {
      // Platform uses schema-local JSON Schema definitions; hoist them for OpenAPI tooling.
      if (key === '$ref' && typeof child === 'string' && child.startsWith('#/definitions/')) {
        const name = child.slice('#/definitions/'.length).replace(/~1/g, '/').replace(/~0/g, '~');
        if (!local[name]) throw new Error('Unresolved embedded definition');
        return [key, local[name]];
      }
      return [key, visit(child, local, depth + 1)];
    }));
  }
  const result = object(visit(input));
  const components = result.components === undefined ? {} : object(result.components);
  const schemas = components.schemas === undefined ? {} : object(components.schemas);
  if (Object.keys(embedded).some(key => Object.hasOwn(schemas, key))) throw new Error('Embedded schema name collision');
  return { ...result, components: { ...components, schemas: { ...schemas, ...embedded } } };
}

function isRecursiveJsonValue(schema: unknown): boolean {
  if (!schema || typeof schema !== 'object') return false;
  const rawChoices = (schema as ObjectValue).anyOf;
  const choices = Array.isArray(rawChoices) ? rawChoices.map(choice =>
    JSON.stringify(choice) === JSON.stringify({ type: 'string', nullable: true, enum: [null] }) ? { type: 'null' } : choice) : rawChoices;
  if (!Array.isArray(choices) || choices.length !== 6) return false;
  const byType = new Map(choices.map(choice => [object(choice).type, object(choice)]));
  if (!['string', 'number', 'boolean', 'null', 'array', 'object'].every(type => byType.has(type))) return false;
  const array = byType.get('array')!;
  const record = byType.get('object')!;
  if (record.propertyNames !== undefined && JSON.stringify(record.propertyNames) !== JSON.stringify({ type: 'string' })) return false;
  const ref = object(array.items).$ref;
  if (Object.keys(object(array.items)).length !== 1 || Object.keys(object(record.additionalProperties)).length !== 1) return false;
  if (typeof ref !== 'string' || object(record.additionalProperties).$ref !== ref) return false;
  // Only normalize the unconstrained recursive JSON-value shape emitted by upstream.
  return choices.every(choice => Object.keys(choice).every(key =>
    ['type', 'items', 'additionalProperties', 'propertyNames'].includes(key)));
}

export function validateSpec(input: unknown): ObjectValue {
  const spec = object(input);
  if (typeof spec.openapi !== 'string' || !/^3\.[01]\./.test(spec.openapi)) throw new Error('Expected OpenAPI 3.0 or 3.1');
  object(spec.paths);
  let nodes = 0;
  function visit(value: unknown, depth = 0): void {
    if (++nodes > 500_000 || depth > 100) throw new Error('Spec exceeds traversal bound');
    if (!value || typeof value !== 'object') return;
    if (!Array.isArray(value) && Object.hasOwn(value, '$ref')) lookup(spec, (value as ObjectValue).$ref);
    for (const child of Object.values(value)) visit(child, depth + 1);
  }
  // Validate before invoking a resolver so even external references in unused schemas cannot fetch.
  visit(spec);
  return spec;
}

export function collectOperations(input: unknown): OperationMetadata[] {
  const spec = validateSpec(qualifyEmbeddedDefinitions(input));
  const ids = new Set<string>();
  const result: OperationMetadata[] = [];
  function resolve(value: unknown, seen = new Set<string>()): ObjectValue {
    const item = object(value);
    if (item.$ref === undefined) return item;
    const ref = item.$ref as string;
    if (seen.has(ref)) throw new Error('Cyclic path or parameter reference');
    const { $ref, ...siblings } = item;
    return { ...resolve(lookup(spec, ref), new Set([...seen, ref])), ...siblings };
  }
  for (const [path, rawPath] of Object.entries(object(spec.paths)).sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0)) {
    if (!path.startsWith('/')) throw new Error('OpenAPI path must be absolute');
    const pathItem = resolve(rawPath);
    for (const method of METHODS) {
      if (pathItem[method] === undefined) continue;
      const op = object(pathItem[method]);
      const id = op.operationId;
      if (typeof id !== 'string' || !id || ids.has(id)) throw new Error('Missing or duplicate operationId');
      ids.add(id);
      const permissions: string[] = [];
      if (op['x-required-permission'] !== undefined) {
        const value = op['x-required-permission'];
        if (typeof value !== 'string' || !value) throw new Error('Invalid required permission');
        permissions.push(value);
      }
      if (op['x-required-permissions'] !== undefined) permissions.push(...strings(op['x-required-permissions']));
      const parameters = new Map<string, ObjectValue>();
      for (const source of [pathItem.parameters ?? [], op.parameters ?? []]) {
        if (!Array.isArray(source)) throw new Error('Invalid operation parameters');
        for (const raw of source) {
          const parameter = resolve(raw);
          if (typeof parameter.in !== 'string' || typeof parameter.name !== 'string') throw new Error('Invalid parameter identity');
          const name = parameter.in === 'header' ? parameter.name.toLowerCase() : parameter.name;
          parameters.set(parameter.in + ':' + name, parameter);
        }
      }
      const key = parameters.get('header:idempotency-key');
      if (key && key.required !== undefined && typeof key.required !== 'boolean') throw new Error('Invalid idempotency requirement');
      result.push({
        operationId: id, method: method.toUpperCase(), path,
        tags: op.tags === undefined ? [] : strings(op.tags),
        access: method === 'get' || method === 'head' ? 'read' : 'write',
        requiredPermissions: permissions.length || op['x-required-permissions'] !== undefined
          ? [...new Set(permissions)].sort() : null,
        idempotency: key ? {
          header: key.name as string, required: key.required === true,
          description: typeof key.description === 'string' ? key.description : null,
        } : null,
      });
    }
  }
  return result;
}

function metadataSource(direct: OperationMetadata[], platform: OperationMetadata[]): string {
  return HEADER + `import type { operations as DirectTypes } from './direct';
import type { operations as PlatformTypes } from './platform';

export type OperationMetadata<Id extends string = string> = {
  readonly operationId: Id;
  readonly method: string;
  readonly path: string;
  readonly tags: readonly string[];
  readonly access: 'read' | 'write';
  readonly requiredPermissions: readonly string[] | null;
  readonly idempotency: { readonly header: string; readonly required: boolean; readonly description: string | null } | null;
};
export const directOperations = ${JSON.stringify(direct, null, 2)} as const satisfies readonly OperationMetadata<keyof DirectTypes>[];
export const platformOperations = ${JSON.stringify(platform, null, 2)} as const satisfies readonly OperationMetadata<keyof PlatformTypes>[];

export type DirectOperationId = typeof directOperations[number]['operationId'];
export type PlatformOperationId = typeof platformOperations[number]['operationId'];
export type DirectOperation<Id extends DirectOperationId> = DirectTypes[Id];
export type PlatformOperation<Id extends PlatformOperationId> = PlatformTypes[Id];
`;
}

export async function generateOutputs(direct: unknown, platform: unknown): Promise<Record<string, string>> {
  const directMeta = collectOperations(direct);
  const platformMeta = collectOperations(platform);
  const outputs: Record<string, string> = {};
  for (const [name, spec] of [['direct', direct], ['platform', platform]] as const) {
    const digest = createHash('sha256').update(JSON.stringify(spec)).digest('hex');
    const ast = await openapiTS(validateSpec(qualifyEmbeddedDefinitions(spec)) as unknown as OpenAPI3, {
      alphabetize: true, silent: true,
      transform(schema, { path }) {
        if (isRecursiveJsonValue(schema)) {
          const ref = (schema.anyOf!.find(choice => (choice as { type?: string }).type === 'array') as { items?: { $ref?: string } }).items?.$ref;
          if (ref === path) return ts.factory.createTypeReferenceNode('JsonValue');
        }
      },
    });
    outputs[name + '.ts'] = HEADER + '// Source SHA-256: ' + digest + '\nexport type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };\n' + astToString(ast);
  }
  outputs['operations.ts'] = metadataSource(directMeta, platformMeta);
  return outputs;
}

async function readSpec(name: string): Promise<unknown> {
  const url = new URL('specs/' + name + '-openapi.json', ROOT);
  if ((await stat(url)).size > MAX_BYTES) throw new Error('Spec exceeds 8 MiB');
  const raw = await readFile(url, 'utf8');
  if (Buffer.byteLength(raw) > MAX_BYTES) throw new Error('Spec exceeds 8 MiB');
  return JSON.parse(raw);
}

export async function main(args: string[]): Promise<void> {
  if (args.length > 1 || (args.length === 1 && args[0] !== '--check')) throw new Error('Usage: generate-operations.ts [--check]');
  const outputs = await generateOutputs(await readSpec('direct'), await readSpec('platform'));
  await writeOutputs(new URL('packages/cli/src/generated/', ROOT), outputs, args[0] === '--check');
  console.log(args.length ? 'Generated operations are current.' : 'Generated Direct and Platform operations.');
}

export async function writeOutputs(directory: URL, outputs: Record<string, string>, check: boolean): Promise<void> {
  if (!check) await mkdir(directory, { recursive: true });
  for (const [name, contents] of Object.entries(outputs)) {
    const path = new URL(name, directory);
    if (check) {
      const current = await readFile(path, 'utf8').catch(() => undefined);
      if (current !== contents) throw new Error('Generated output is stale: ' + name + '; run bun run operations:generate');
    } else {
      await writeFile(path, contents);
    }
  }
}

if (import.meta.main) main(process.argv.slice(2)).catch(() => {
  console.error('Operation generation/check failed. Check local specs and run bun run operations:generate after review.');
  process.exitCode = 1;
});
